### ISSUE TITLE
HAZniCS software

### ISSUE THREAD

**Issue by anabudisa** [scientificcomputing/scientificcomputing.github.io#11]
[This software](https://github.com/HAZmathTeam/hazmath/tree/main/examples/haznics) is related to the paper [HAZniCS - Software Components for Multiphysics Problems](https://arxiv.org/abs/2210.13274) and the demos in the paper are already [linked](https://github.com/anabudisa/HAZniCS-examples) in one of the "add-repo" issues here.

The software can be installed via script `install_haznics.sh` which is available [here](https://github.com/HAZmathTeam/hazmath/blob/main/examples/haznics/install_haznics.sh) and there is a [README](https://github.com/HAZmathTeam/hazmath/blob/main/examples/haznics/README.md) file that should help with installation. Long story short, this creates a Python library `haznics.py` from the present code in the parent directory/repo (which is mostly in C/C++) and installs all dependencies for the demos. 

To be able to do `import haznics` in any script, we link the library with running `source setup.rc`. 

I wish this was simpler, but here we are. If you have any recommendations on easier installation/workflow for this software, I welcome all the help.

**Comment by anabudisa** [comment]
Thanks a lot, we can then add `haznics` as a separate package.

> I guess we can make a Docker image that has all these dependencies? Do you want me to have a go at that?

If you have time, yes please! I can help, just let me know. (I tried making a docker image before using a legacy FEniCS docker image, but failed because I couldn't update `cmake` to a usable version)

**Comment by jorgensd** [comment]
@anabudisa I've made a code that works (at least for `test_haznics.py`. You need the following two files:
`environment.yml`
```yaml
name: test-env
channels:
  - conda-forge
dependencies:
  - fenics-dolfin
  - quadpy
  - git
  - pip
  - swig
  - pip:
    - git+https://github.com/MiroK/fenics_ii
    - git+https://bitbucket.org/fenics-apps/cbc.block.git
    - git+https://github.com/MiroK/ulfy.git
```
`Dockerfile`
```docker
# Use Docker image with preinstalled conda
FROM condaforge/mambaforge 

WORKDIR /source/

ENV DEBIAN_FRONTEND=noninteractive


# Install ssh (missing dependency to run conda envs)
RUN apt-get update && \
    apt-get install -y ssh build-essential gfortran

# Upgrade mamba
RUN mamba upgrade -y mamba

# Copy environment file into docker env
COPY environment.yml .

# Update environment file with new environment name
RUN mamba env update --file environment.yml --name dockerenv


SHELL ["conda", "run", "-n", "dockerenv", "/bin/bash", "-c"]

RUN git clone https://github.com/HAZmathTeam/hazmath && \
    cd hazmath && \ 
    make config shared=yes suitesparse=yes lapack=yes haznics=yes swig=yes . && \
    make install

ENV PYTHONPATH /source/hazmath/swig_files:${PYTHONPATH}

RUN echo "source activate dockerenv" > ~/.bashrc

ENTRYPOINT ["/bin/bash"]
```

You can build this locally on your computer (if you have Docker) by calling
` docker build -t hazmat .`
and run it with
` docker run -ti --network=host -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd):/haznics -w /haznics --rm --shm-size=512m hazmat`
Feel free to test it and give me any feedback.
We could also chat tomorrow about how to add this to Dockerhub or somewhere else as a GitHub Package.

**Comment by anabudisa** [comment]
@jorgensd Thanks a lot, the docker works, except that I needed to re-compile the hazmath library within the running container. But other than that, demos and test examples run fine. :)

**Comment by jorgensd** [comment]
> @jorgensd Thanks a lot, the docker works, except that I needed to re-compile the hazmath library within the running container. But other than that, demos and test examples run fine. :)

You shouldn't need to do that. They should run fine without recompilation. Could you point me to an example where this is the case?
